version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - echo $ECR_REPONAME
      - echo $ECR_URI
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v4j2a7d2
      #- REPOSITORY_NAME="ecr-repo"      
      #- REPOSITORY_URI=public.ecr.aws/v4j2a7d2/ecr-repo

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPONAME:latest .
      - docker tag $ECR_REPONAME:latest $ECR_URI:latest
  post_build:
    commands:
      - docker push $ECR_REPONAME:latest
      - printf '[{"name":"node","imageUri":"%s"}]' $ECR_URI:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
