version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - $ECR_REPONAME
      - $$ECR_REPONAME
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v4j2a7d2
      #- REPOSITORY_NAME="ecr-repo"      
      #- REPOSITORY_URI=public.ecr.aws/v4j2a7d2/ecr-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPONAME:latest .
      - docker tag $ECR_REPONAME:latest $ECR_REPONAME:latest
#       - docker tag $ECR_REPONAME:latest $ECR_REPONAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $ECR_REPONAME:latest
      - printf '[{"name":"golang-container","imageUri":"%s"}]' $ECR_REPONAME:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
